version: '3.6'
services:
    vosint-api:
        image: vienai/vosint-api:1.0.2
        ports:
            - 3688:6102
        deploy:
            restart_policy:
                condition: on-failure
            replicas: 1
            placement:
                constraints:
                    - node.hostname==srv1

        volumes:
            - vosint_backend_static:/usr/app/static
        networks:
            - vosint3_system_network

volumes:
    vosint_backend_static:
        driver: local
        name: vosint_backend_static
        driver_opts:
            type: none
            o: bind
            device: "/home/vosint/deployment/static"

networks:
    vosint3_system_network:
        external: true
